name: check

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run unit tests
        run: python -m pytest tests/ -s -v
