name: deploy-prod

on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
    branches:
      - prod

jobs:
  aws-deploy:
    uses: "./.github/workflows/aws-deploy.yaml"
    with:
      role-to-assume: "arn:aws:iam::878654265857:role/sagebase-github-oidc-sage-bionetworks-schematic-infra"
      role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
