name: pre-deploy-check

on:
  workflow_run:
    workflows:
      - check
    types:
      - completed
    branches: [dev, stage, prod]

jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Generate cloudformation
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          actions_comment: false
          debug_log: true
          cdk_args: '--output ./cdk.out'
